version: '3.3'

services:
    web-curriculo:
        build: ./
        ports:
            - 8000:80
        volumes:
            - ./:/usr/share/nginx/html
        restart: always
        networks:
            - docker
    db:
        image: mysql
        restart: always
        ports:
            - 3308:3306
        environment:
            MYSQL_ROOT_PASSWORD: docker
            MYSQL_DATABASES: web_curriculo
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
        networks:
            - docker
networks:
    docker:
        driver: bridge
